### ISSUE TITLE
corrigendum to Contract notice – utilities (TED F05), 500 Internal Server Error

### ISSUE THREAD

**Issue by esaiko** [Hankintailmoitukset/hilma-api#1]
**Description**:
User is trying to publish correction (corrigendum) to a notice of type  Contract notice – utilities (TED F05).
Validation (PUSH) is passed without errors.
Publishing (PUT) fails with Hilma response 500 Internal error.

**To Reproduce:**
Use the request described below and send the json payload (which is mailed separately to support).

````
curl -d @500-error.json -H 'Ocp-Apim-Subscription-Key: ed43xxx' -H 'Content-Type: application/json' -X PUT https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/627?projectId=29532&parentId=584
````
**Request headers:**
````
PUT https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/627?projectId=29532&parentId=584
Content-Length: 6095
Ocp-Apim-Subscription-Key: ed43xxx
Content-Type: application/json
````
**Request body:**
``` json
{
    "type": 500,
    "communicationInformation": {
        "procurementDocumentsAvailable": 1,
        "procurementDocumentsUrl": "https://fakeaddress.com",
        "additionalInformation": 1,
        "sendTendersOption": 1,
        "electronicAddressToSendTenders": "https://fakeaddress.com"
    },
    "contactPerson": {
        "name": "Aku Ankka",
        "phone": "+358 123123123",
        "email": "fake.address@example.com"
    },
    "links": [
        {
            "url": "https://fakeaddress.com"
        }
    ],
    "lotsInfo": {
        "divisionLots": false
    },
    "mainCPVCode": {
        "code": "32442200",
        "name": "Kaukokirjoittimet"
    },
    "objectDescriptions": [
        {
            "lotNumber": 1,
            "additionalCpvCodes": [
                {
                    "code": "32442200",
					"name": "Kaukokirjoittimet"
                }
            ],
            "nutsCodes": [
                "FI"
            ],
            "descrProcurement": [
                "Description"
            ],
            "additionalInformation": [
                "Desc 1",
                "Desc 2"
            ],
            "awardCriteria": {
                "criterionTypes": 8
            },
            "timeFrame": {
                "type": 3,
                "beginDate": "2020-08-01T00:00:00",
                "endDate": "2021-13-31T00:00:00"
            },
            "optionsAndVariants": {
                "variantsWillBeAccepted": false
            },
            "euFunds": {
                "procurementRelatedToEuProgram": false
            }
        }
    ],
    "organisation": {
        "information": {
            "officialName": "Firma Oy",
            "nationalRegistrationNumber": "111111-6",
            "nutsCodes": [
                "FI1"
            ],
            "postalAddress": {
                "streetAddress": "Osoite 1 A 1",
                "postalCode": "01600",
                "town": "Vantaa",
                "country": "FI"
            },
            "telephoneNumber": "+358 123123",
            "email": "fake.address@example.com",
            "mainUrl": "http://fakeaddress.com"
        },
        "contractingAuthorityType": 64,
        "otherContractingAuthorityType": "Yhteishankintayksikkö",
        "mainActivityUtilities": 1024,
        "otherMainActivity": "Muuaktiviteetti"
    },
    "project": {
        "contractType": 1,
        "referenceNumber": "123456",
        "title": "Procurement title",
        "procurementCategory": 1,
        "jointProcurement": true,
        "coPurchasers": [
            {
                "officialName": "Partner 1",
                "nationalRegistrationNumber": "111111-6",
                "nutsCodes": [
                    "FI"
                ],
                "postalAddress": {
                    "town": "Vantaa",
                    "postalCode": "01600",
                    "country": "FI"
                },
                "email": "fake@address.com",
                "mainUrl": "https://fakeaddress.com"
            }
        ],
        "centralPurchasing": true
    },
    "shortDescription": [
        "Short description"
    ],
    "tenderingInformation": {
        "tendersOrRequestsToParticipateDueDateTime": "2020-02-29T12:00:00",
        "languages": [
            "FI"
        ],
        "tendersMustBeValidOption": 1,
        "tendersMustBeValidUntil": "2020-08-31T16:00:00",
        "tenderOpeningConditions": {
            "openingDateAndTime": "2020-03-27T12:05:00",
            "informationAboutAuthorisedPersons": [
                "Information"
            ]
        }
    },
    "language": "FI",
    "procedureInformation": {
        "procedureType": 1,
        "procurementGovernedByGPA": true
    },
    "proceduresForReview": {
        "reviewBody": {
            "officialName": "Markkinaoikeus",
            "nationalRegistrationNumber": null,
            "nutsCodes": [
                "FI"
            ],
            "postalAddress": {
                "streetAddress": "Radanrakentajantie 5",
                "town": "Helsinki",
                "postalCode": "00520",
                "country": "FI"
            },
            "telephoneNumber": "+358 295643300",
            "email": "markkinaoikeus@oikeus.fi",
            "mainUrl": "http://www.oikeus.fi/markkinaoikeus"
        }
    },
    "legalBasis": "32014L0025",
    "hilmaStatistics": {
        "energyEfficiencyConsidered": false,
        "innovationConsidered": false,
        "smeParticipationConsidered": false
    },
    "isCorrigendum": true,
    "corrigendumAdditionalInformation": [
        "Changed",
        "",
        "*Stuff",
        "*other stuff"
    ]
}
```

**API Response**:
````
500 Internal Server Error
Content-Length: 0
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Fri, 24 Jan 2020 08:11:43 GMT
Connection: close
````

**Expected behavior** 
Because the payload passed the validation phase (PUSH) we expect it to be accepted by Hilma

**Comment by jannef** [comment]
Please use the issue template found [here](https://github.com/Hankintailmoitukset/hilma-api/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by jannef** [comment]
Request body was missing, from the issue:

`
{
    "type": 500,
    "communicationInformation": {
        "procurementDocumentsAvailable": 1,
        "procurementDocumentsUrl": "https://fakeaddress.com",
        "additionalInformation": 1,
        "sendTendersOption": 1,
        "electronicAddressToSendTenders": "https://fakeaddress.com"
    },
    "contactPerson": {
        "name": "Aku Ankka",
        "phone": "+358 123123123",
        "email": "fake.address@example.com"
    },
    "links": [
        {
            "url": "https://fakeaddress.com"
        }
    ],
    "lotsInfo": {
        "divisionLots": false
    },
    "mainCPVCode": {
        "code": "32442200",
        "name": "Kaukokirjoittimet"
    },
    "objectDescriptions": [
        {
            "lotNumber": 1,
            "additionalCpvCodes": [
                {
                    "code": "32442200",
					"name": "Kaukokirjoittimet"
                }
            ],
            "nutsCodes": [
                "FI"
            ],
            "descrProcurement": [
                "Description"
            ],
            "additionalInformation": [
                "Desc 1",
                "Desc 2"
            ],
            "awardCriteria": {
                "criterionTypes": 8
            },
            "timeFrame": {
                "type": 3,
                "beginDate": "2020-08-01T00:00:00",
                "endDate": "2021-13-31T00:00:00"
            },
            "optionsAndVariants": {
                "variantsWillBeAccepted": false
            },
            "euFunds": {
                "procurementRelatedToEuProgram": false
            }
        }
    ],
    "organisation": {
        "information": {
            "officialName": "Firma Oy",
            "nationalRegistrationNumber": "111111-6",
            "nutsCodes": [
                "FI1"
            ],
            "postalAddress": {
                "streetAddress": "Osoite 1 A 1",
                "postalCode": "01600",
                "town": "Vantaa",
                "country": "FI"
            },
            "telephoneNumber": "+358 123123",
            "email": "fake.address@example.com",
            "mainUrl": "http://fakeaddress.com"
        },
        "contractingAuthorityType": 64,
        "otherContractingAuthorityType": "Yhteishankintayksikkö",
        "mainActivityUtilities": 1024,
        "otherMainActivity": "Muuaktiviteetti"
    },
    "project": {
        "contractType": 1,
        "referenceNumber": "123456",
        "title": "Procurement title",
        "procurementCategory": 1,
        "jointProcurement": true,
        "coPurchasers": [
            {
                "officialName": "Partner 1",
                "nationalRegistrationNumber": "111111-6",
                "nutsCodes": [
                    "FI"
                ],
                "postalAddress": {
                    "town": "Vantaa",
                    "postalCode": "01600",
                    "country": "FI"
                },
                "email": "fake@address.com",
                "mainUrl": "https://fakeaddress.com"
            }
        ],
        "centralPurchasing": true
    },
    "shortDescription": [
        "Short description"
    ],
    "tenderingInformation": {
        "tendersOrRequestsToParticipateDueDateTime": "2020-02-29T12:00:00",
        "languages": [
            "FI"
        ],
        "tendersMustBeValidOption": 1,
        "tendersMustBeValidUntil": "2020-08-31T16:00:00",
        "tenderOpeningConditions": {
            "openingDateAndTime": "2020-03-27T12:05:00",
            "informationAboutAuthorisedPersons": [
                "Information
            ]
        }
    },
    "language": "FI",
    "procedureInformation": {
        "procedureType": 1,
        "procurementGovernedByGPA": true
    },
    "proceduresForReview": {
        "reviewBody": {
            "officialName": "Markkinaoikeus",
            "nationalRegistrationNumber": null,
            "nutsCodes": [
                "FI"
            ],
            "postalAddress": {
                "streetAddress": "Radanrakentajantie 5",
                "town": "Helsinki",
                "postalCode": "00520",
                "country": "FI"
            },
            "telephoneNumber": "+358 295643300",
            "email": "markkinaoikeus@oikeus.fi",
            "mainUrl": "http://www.oikeus.fi/markkinaoikeus"
        }
    },
    "legalBasis": "32014L0025",
    "hilmaStatistics": {
        "energyEfficiencyConsidered": false,
        "innovationConsidered": false,
        "smeParticipationConsidered": false
    },
    "isCorrigendum": true,
    "corrigendumAdditionalInformation": [
        "Changed",
        "",
        "*Stuff",
        "*other stuff"
    ]
}
`

**Comment by jannef** [comment]
There is a fix for this issue pending a deployment to production. Issue is caused by incorrect handling of changes to Co Purchasers. Please retry the request once the fix has been deployed.

**Comment by jannef** [comment]
Issue has been fixed and deployed to production. Please try sending the notice again.

**Comment by esaiko** [comment]
User has tried sending the same notice again but it still failes with internal error.

**Request headers**
````
PUT https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/627?projectId=29532&parentId=584
Content-Length: 6095
Ocp-Apim-Subscription-Key: ed435xxxxx
Content-Type: application/json
````

(payload is sent by email to support)


Response
````
500 Internal Server Error
Content-Length: 0
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Fri, 24 Jan 2020 11:53:30 GMT
Connection: close
````

**Comment by tuomastolvanen** [comment]
There was an techincal issue releated to handling of null value for corrigendum notices. The fix for the issue has been released. 

During the investigation we identified the more fundamental content related issue to be that the F14 cannot handle changes to coPurcasers. Only small corrections are allowed with F14, and therefore major chenges in the procurement should be done by cancelling and creating a new contract notice. 
We are going to clarify what information can be changed with corrigendums in Hilma and will inform about the restrictions.
