### ISSUE TITLE
Corrigendum (national) showing unrelated changes

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#17]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
While IncludesFrameworkAgreement is false, changing value in FrameworkAgreementType shows up in summary of amendments

**To Reproduce**
Original notice:
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_6177

{"CommunicationInformation":{"ProcurementDocumentsAvailable":1,"ProcurementDocumentsUrl":"https://tarjouspalvelu.fi/pori?id=284819&tpk=fd806996-39f0-4e91-89a3-663c64bf8428","AdditionalInformation":1,"AdditionalInformationAddress":{"OfficialName":"Porin kaupunki","NationalRegistrationNumber":"0137323-9","NutsCodes":[],"PostalAddress":{"StreetAddress":"PL 121","PostalCode":"28101","Town":"Pori","Country":"FI"},"TelephoneNumber":"+358 447017641","Email":"tarjous@pori.fi","MainUrl":"https://www.pori.fi/tyo-ja-yrittaminen/hankinnat"},"SendTendersOption":1,"ElectronicAddressToSendTenders":"https://tarjouspalvelu.fi/pori?id=284819&tpk=fd806996-39f0-4e91-89a3-663c64bf8428","ElectronicCommunicationRequiresSpecialTools":false,"DocumentsEntirelyInHilma":false,"SpecsAndAdditionalDocuments":0},"ComplementaryInformation":{"IsRecurringProcurement":false,"ElectronicOrderingUsed":false,"ElectronicInvoicingUsed":false,"ElectronicPaymentUsed":false},"ConditionsInformation":{"EconomicCriteriaToParticipate":false,"TechnicalCriteriaToParticipate":false,"RestrictedToShelteredWorkshop":false,"RestrictedToShelteredProgram":false,"ReservedOrganisationServiceMission":false,"ExecutionOfServiceIsReservedForProfession":false,"ObligationToIndicateNamesAndProfessionalQualifications":false},"ContactPerson":{"Email":"tarjous@pori.fi","Phone":"+358 447017641"},"EstimatedValue":{"Type":1,"Value":1200000.00,"DisagreeToBePublished":true},"LotsInfo":{"DivisionLots":false,"LotsSubmittedFor":0,"LotsMaxAwarded":false},"MainCpvCode":{"Code":"45000000","Name":"Rakennustyöt","VocCodes":[]},"ObjectDescriptions":[{"MainCpvCode":{"Code":"45000000","Name":"Rakennustyöt","VocCodes":[]},"AdditionalCpvCodes":[],"NutsCodes":["FI196"],"DescrProcurement":["Katso kohta II.1.4) Lyhyt kuvaus *. "],"AgreeAwardCriteriaToBePublished":true,"AwardCriteria":{"CriterionTypes":8},"AwardContract":{"ContractAwarded":1,"NoAwardedContract":null,"AwardedContract":{"ConclusionDate":"2020-04-01T00:00:00","ContractNumber":null,"ContractTitle":"Uuden lastensuojelulaitoksen rakentaminen SR-urakkana","NumberOfTenders":{"DisagreeTenderInformationToBePublished":null,"Total":0,"Sme":0,"OtherEu":0,"NonEu":0,"Electronic":0},"DisagreeContractorInformationToBePublished":null,"Contractors":[],"InitialEstimatedValueOfContract":{"Value":1200000.0},"FinalTotalValue":null,"LikelyToBeSubcontracted":false,"ExAnteSubcontracting":null,"PricePaidForBargainPurchases":null,"NotPublicFields":{"CommunityOrigin":false,"NonCommunityOrigin":true,"Countries":[],"AwardedToTendererWithVariant":false,"AbnormallyLowTendersExcluded":false},"ConcessionRevenue":null,"PricesAndPayments":null,"ConcessionValueAdditionalInformation":null}},"EstimatedValue":null,"TimeFrame":{"Type":3,"BeginDate":"2020-04-01T00:00:00","EndDate":"2021-07-31T00:00:00","CanBeRenewed":false},"CandidateNumberRestrictions":{},"OptionsAndVariants":{"VariantsWillBeAccepted":false,"Options":false,"OptionType":0,"OptionsDays":0,"OptionsMonths":0},"TendersMustBePresentedAsElectronicCatalogs":false,"EuFunds":{}}],"Organisation":{"Information":{"OfficialName":"Porin kaupunki","NationalRegistrationNumber":"0137323-9","NutsCodes":[],"PostalAddress":{"StreetAddress":"PL 121","PostalCode":"28101","Town":"Pori","Country":"FI"},"TelephoneNumber":"+358 447017641","Email":"tarjous@pori.fi","MainUrl":"https://www.pori.fi/tyo-ja-yrittaminen/hankinnat"},"ContractingAuthorityType":4,"MainActivity":1},"Project":{"ContractType":4,"ReferenceNumber":"PRIDno-2020-479","Title":"Uuden lastensuojelulaitoksen rakentaminen SR-urakkana","JointProcurement":false,"CoPurchasers":[],"CentralPurchasing":false},"PublishToTed":false,"ShortDescription":["Porin kaupungin tekninen toimiala pyytää tarjouksia Perusturvakeskuksen tarpeeseen toteutetusta lastensuojelun 7+7 paikkaisesta yksiköstä tämän tarjouspyynnön ja sen liitteiden mukaisesti. Hankinta toteutetaan SR-urakkana.","","Rakennuskohde käsittää Porin kaupungin teknisen toimialan suunnittelu- ja rakentamishankkeen suunnittelun, lupien hakemisen ja rakentamisen urakkaohjelman ja muiden oheisten urakkalaskenta-asiapaperien mukaisesti.","","Kohteen kuvaus:","","Hankkeessa rakennetaan uusi lastensuojelulaitos piha-alueineen. Rakennuksen toiminnallisuudelle on asetettu lastensuojelulain mukaiset vaatimukset.","","Rakennuksen tavoitteena on luoda viihtyisä kokonaisuus, jossa on hyvä ja kodikas ilmapiiri. Tilojen suunnittelussa painotetaan monipuolisuutta ja kustannustehokkuutta.","","Rakennuspaikkana on Y-tontti nro 19, Radioasemantie, 28330, Pori"],"Type":9902,"TenderingInformation":{"TendersOrRequestsToParticipateDueDateTime":"2020-03-09T12:00:00","Languages":["FI"],"TendersMustBeValidOption":2,"TendersMustBeValidForMonths":3,"TenderOpeningConditions":{"OpeningDateAndTime":"2020-03-09T12:01:00"}},"Language":"FI","ProcedureInformation":{"ProcedureType":1,"FrameworkAgreement":{"IncludesFrameworkAgreement":false,"FrameworkAgreementType":1,"EnvisagedNumberOfParticipants":null,"FrameworkEnvisagedType":0,"IncludesDynamicPurchasingSystem":false,"DynamicPurchasingSystemInvolvesAdditionalPurchasers":false,"DynamicPurchasingSystemWasTerminated":false,"EstimatedTotalValue":null,"Duration":null},"ElectronicAuctionWillBeUsed":false},"ProceduresForReview":{"ReviewBody":{"OfficialName":"Markkinaoikeus","NutsCodes":[],"PostalAddress":{"StreetAddress":"Radanrakentajantie 5","PostalCode":"00520","Town":"Helsinki","Country":"FI"},"TelephoneNumber":"+358 295643300","Email":"markkinaoikeus@oikeus.fi","MainUrl":"http://www.oikeus.fi/markkinaoikeus"}},"IsCorrigendum":false,"ContractAwardsDefence":null}

Corrigendum:
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_9659

{"CommunicationInformation":{"ProcurementDocumentsAvailable":1,"ProcurementDocumentsUrl":"https://tarjouspalvelu.fi/pori?id=284819&tpk=fd806996-39f0-4e91-89a3-663c64bf8428","AdditionalInformation":1,"AdditionalInformationAddress":{"OfficialName":"Porin kaupunki","NationalRegistrationNumber":"0137323-9","NutsCodes":[],"PostalAddress":{"StreetAddress":"PL 121","PostalCode":"28101","Town":"Pori","Country":"FI"},"TelephoneNumber":"+358 447017641","Email":"tarjous@pori.fi","MainUrl":"https://www.pori.fi/tyo-ja-yrittaminen/hankinnat"},"SendTendersOption":1,"ElectronicAddressToSendTenders":"https://tarjouspalvelu.fi/pori?id=284819&tpk=fd806996-39f0-4e91-89a3-663c64bf8428","ElectronicCommunicationRequiresSpecialTools":false,"DocumentsEntirelyInHilma":false,"SpecsAndAdditionalDocuments":0},"ComplementaryInformation":{"IsRecurringProcurement":false,"ElectronicOrderingUsed":false,"ElectronicInvoicingUsed":false,"ElectronicPaymentUsed":false},"ConditionsInformation":{"EconomicCriteriaToParticipate":false,"TechnicalCriteriaToParticipate":false,"RestrictedToShelteredWorkshop":false,"RestrictedToShelteredProgram":false,"ReservedOrganisationServiceMission":false,"ExecutionOfServiceIsReservedForProfession":false,"ObligationToIndicateNamesAndProfessionalQualifications":false},"ContactPerson":{"Email":"tarjous@pori.fi","Phone":"+358 447017641"},"EstimatedValue":{"Type":1,"Value":1200000.00,"DisagreeToBePublished":true},"LotsInfo":{"DivisionLots":false,"LotsSubmittedFor":0,"LotsMaxAwarded":false},"MainCpvCode":{"Code":"45000000","Name":"Rakennustyöt","VocCodes":[]},"ObjectDescriptions":[{"MainCpvCode":{"Code":"45000000","Name":"Rakennustyöt","VocCodes":[]},"AdditionalCpvCodes":[],"NutsCodes":["FI196"],"DescrProcurement":["Katso kohta II.1.4) Lyhyt kuvaus *. "],"AgreeAwardCriteriaToBePublished":true,"AwardCriteria":{"CriterionTypes":8},"AwardContract":{"ContractAwarded":1,"NoAwardedContract":null,"AwardedContract":{"ConclusionDate":"2020-04-01T00:00:00","ContractNumber":null,"ContractTitle":"Uuden lastensuojelulaitoksen rakentaminen SR-urakkana","NumberOfTenders":{"Total":0,"Electronic":0},"DisagreeContractorInformationToBePublished":null,"Contractors":[],"InitialEstimatedValueOfContract":{"Value":1200000.00},"FinalTotalValue":null,"LikelyToBeSubcontracted":false,"ExAnteSubcontracting":null,"PricePaidForBargainPurchases":null,"NotPublicFields":{"CommunityOrigin":false,"NonCommunityOrigin":true,"Countries":[],"AwardedToTendererWithVariant":false,"AbnormallyLowTendersExcluded":false},"ConcessionRevenue":null,"PricesAndPayments":null,"ConcessionValueAdditionalInformation":null}},"EstimatedValue":null,"TimeFrame":{"Type":3,"BeginDate":"2020-04-01T00:00:00","EndDate":"2021-07-31T00:00:00","CanBeRenewed":false},"CandidateNumberRestrictions":{},"OptionsAndVariants":{"VariantsWillBeAccepted":false,"Options":false,"OptionType":0,"OptionsDays":0,"OptionsMonths":0},"TendersMustBePresentedAsElectronicCatalogs":false,"EuFunds":{"ProcurementRelatedToEuProgram":false}}],"Organisation":{"Information":{"OfficialName":"Porin kaupunki","NationalRegistrationNumber":"0137323-9","NutsCodes":[],"PostalAddress":{"StreetAddress":"PL 121","PostalCode":"28101","Town":"Pori","Country":"FI"},"TelephoneNumber":"+358 447017641","Email":"tarjous@pori.fi","MainUrl":"https://www.pori.fi/tyo-ja-yrittaminen/hankinnat"},"ContractingAuthorityType":4,"MainActivity":1},"Project":{"Id":30975,"ContractType":4,"ReferenceNumber":"PRIDno-2020-479","Title":"Uuden lastensuojelulaitoksen rakentaminen SR-urakkana","JointProcurement":false,"CoPurchasers":[],"CentralPurchasing":false},"PublishToTed":false,"ShortDescription":["Porin kaupungin tekninen toimiala pyytää tarjouksia Perusturvakeskuksen tarpeeseen toteutetusta lastensuojelun 7+7 paikkaisesta yksiköstä tämän tarjouspyynnön ja sen liitteiden mukaisesti. Hankinta toteutetaan SR-urakkana.","","Rakennuskohde käsittää Porin kaupungin teknisen toimialan suunnittelu- ja rakentamishankkeen suunnittelun, lupien hakemisen ja rakentamisen urakkaohjelman ja muiden oheisten urakkalaskenta-asiapaperien mukaisesti.","","Kohteen kuvaus:","","Hankkeessa rakennetaan uusi lastensuojelulaitos piha-alueineen. Rakennuksen toiminnallisuudelle on asetettu lastensuojelulain mukaiset vaatimukset.","","Rakennuksen tavoitteena on luoda viihtyisä kokonaisuus, jossa on hyvä ja kodikas ilmapiiri. Tilojen suunnittelussa painotetaan monipuolisuutta ja kustannustehokkuutta.","","Rakennuspaikkana on Y-tontti nro 19, Radioasemantie, 28330, Pori"],"Type":9902,"TenderingInformation":{"TendersOrRequestsToParticipateDueDateTime":"2020-03-16T12:00:00","Languages":["FI"],"TendersMustBeValidOption":2,"TendersMustBeValidForMonths":3,"TenderOpeningConditions":{"OpeningDateAndTime":"2020-03-09T12:01:00"}},"Language":"FI","ProcedureInformation":{"ProcedureType":1,"FrameworkAgreement":{"IncludesFrameworkAgreement":false,"IncludesDynamicPurchasingSystem":false,"DynamicPurchasingSystemInvolvesAdditionalPurchasers":false},"ElectronicAuctionWillBeUsed":false},"ProceduresForReview":{"ReviewBody":{"OfficialName":"Markkinaoikeus","NutsCodes":[],"PostalAddress":{"StreetAddress":"Radanrakentajantie 5","PostalCode":"00520","Town":"Helsinki","Country":"FI"},"TelephoneNumber":"+358 295643300","Email":"markkinaoikeus@oikeus.fi","MainUrl":"http://www.oikeus.fi/markkinaoikeus"}},"IsCorrigendum":true,"ContractAwardsDefence":null}

**Expected behavior**
Summary of amendments about FrameworkAgreementType should not be visible as no FrameworkAgreement is used.

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
A fix is coming to this in the near future.
Be also advised, that there is a ticket coming to our backlog where we will validate which fields are allowed to be fixed. If the field is not allowed, Hilma will return an error.

**Comment by arinurkkala** [comment]
Hilma was updated yesterday. Should work now.

**Comment by cloudia-jt** [comment]
What was the fix? Notice in Hilma still shows FrameworkAgreementType change

**Comment by arinurkkala** [comment]
It was a code fix. In the future, this change shouldn't appear.
I have now removed the unnecessary change from Hilma as well.
