### ISSUE TITLE
Error in saving data, eForms notices

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#226]
**Describe the bug**
The Hilma UI gives an error when the user is saving data on notice draft.

**To Reproduce**

- A notice has been created in HILMA test environment
- Notice is created through draft API
- The user is on "Ilmoituksen yleiset tiedot" page.
- The user tries to save the data
- The system gives an error
- The error can be bypassed by saving the data on "Ilmoituksen tiedot" page.

**Expected behavior**
No errors in HIlma UI when saving data.

**API response**
<img width="805" alt="Console_error" src="https://github.com/user-attachments/assets/e7400927-64f7-44e7-8ff7-65653ed9d097">

https://github.com/user-attachments/assets/e4112602-488f-4ed7-aaaa-be2e24812ba6

**Additional context**
The issue is the same as Notice error when saving (test environment) #223.

**Comment by Stugeh** [comment]
I've created internal tickets. We'll begin investigation asap.

**Comment by JarkkoSi** [comment]
@OlliSurakka Has this issue been recurring in the last 6 months or can we confidently say that this has been resolved?

**Comment by ScRistinen** [comment]
No this is not resolved. At least in test environment this occurs with every draft notice if user navigates to  "Ilmoituksen yleiset tiedot" view before "Ilmoituksen tiedot" view. Error happens on save or when view is changed.

**Comment by ScRistinen** [comment]
Has there been any progress in solving this problem?

**Comment by PaulaKainiemi** [comment]
Hi @ScRistinen,
The test environment was updated last week, so now you can try this again.
